version: 2

project_name: acto

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/acto
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X "main.version={{.Version}}"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: acto
    repository:
      owner: yldio
      name: acto
    directory: homebrewFormula
    commit_author:
      name: 'github-actions[bot]'
      email: '41898282+github-actions[bot]@users.noreply.github.com'
    homepage: https://github.com/yldio/acto#readme
    description: A tool that converts HCL files to GitHub Actions YAML's workflow files.
    license: MIT
    install: |
      bin.install "acto"
      man1.install "man/acto.1"
    test: |
      system "#{bin}/acto -version"

changelog:
  disable: true