# This file was generated by GoReleaser. DO NOT EDIT.
cask "cinzel" do
  name "cinzel"
  desc "Bidirectional converter between HCL and CI/CD YAML"
  homepage "https://github.com/yldio/cinzel"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cinzel"

  on_macos do
    on_intel do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_darwin_amd64.tar.gz"
      sha256 "51af56bf3336baf5fe3ade3e75ec5eff9f18dfb7a5b8c7f2a88fd5ec02411a9f"
    end
    on_arm do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_darwin_arm64.tar.gz"
      sha256 "47c2633facb56c984f6dd61a7dac2942616831bb4e14fe23b17355f1085dad1e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_linux_amd64.tar.gz"
      sha256 "2ae23073a21c70037589c707cc149b373d501c95ca504c67f0e5fe439ad79b7f"
    end
    on_arm do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_linux_arm64.tar.gz"
      sha256 "8bc7a8ffddb1ea2d450c1316ac23333b7f9d15a39bba8b4fcb97b5a2c3634a7b"
    end
  end

  # No zap stanza required
end
