# This file was generated by GoReleaser. DO NOT EDIT.
cask "cinzel" do
  name "cinzel"
  desc "Bidirectional converter between HCL and CI/CD YAML"
  homepage "https://github.com/yldio/cinzel"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cinzel"

  on_macos do
    on_intel do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_darwin_amd64.tar.gz"
      sha256 "f83f449bb9a12976087ee0fd51c84ed82660d6a990677b0153f9592ad5972265"
    end
    on_arm do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_darwin_arm64.tar.gz"
      sha256 "4477fee2fcb6e87c16a6be20821f75ae50c36a4c0cc1204dc604e534f0a5166f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_linux_amd64.tar.gz"
      sha256 "8e7544839ffd5d34c19b4553dcbe451c5cf7316a8661ddc05a20b9fcaab44db0"
    end
    on_arm do
      url "https://github.com/yldio/cinzel/releases/download/v#{version}/cinzel_#{version}_linux_arm64.tar.gz"
      sha256 "19b1db80302e5c9602b0aa5b1033cf4db550f3992e79b722c2bcde2134882fb1"
    end
  end

  # No zap stanza required
end
