# Copyright 2026 YLD Limited
# SPDX-License-Identifier: Apache-2.0

name: "Bug report"
description: Report a bug
labels: ["bug", "triage"]
title: "[Bug]: "
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please add as much details as possible regarding this bug
      placeholder: Fill with details...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/yldio/cinzel/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: contrutions
    attributes:
      label: Contributing
      description: You have read our [Contributing](https://github.com/yldio/cinzel/CONTRIBUTING.md) guide.
      options:
        - label: I have read and checked this is not a duplicated issue
          required: true
