name: Suggest Feature
description: Suggest a feature / enhancement
labels: ["needs_pointing"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: Please add as more details as possible regarding this ticket
      placeholder: Fill with details
    validations:
      required: true
  - type: textarea
    id: feature-ac
    attributes:
      label: Acceptance Criteria
      description: Please add all acceptance criteria here
      placeholder: "- [ ] Describe each acceptance criteria as a checkbox"
    validations:
      required: true