name: Pull Request
on:
  pull_request:
permissions:
  contents: read
  pull-requests: write
jobs:
  pull_request:
    name: "${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: "false"
      - id: mise_setup
        name: Setup mise
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db
        with:
          cache: "true"
          install: "true"
      - id: tests
        name: Tests
        run: mise run test-ci
      - id: coverage
        if: "${{ matrix.os == 'ubuntu-24.04' }}"
        name: Coverage
        uses: gwatts/go-coverage-action@2845595538a59d63d1bf55f109c14e104c6f7cb3
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
          - windows-2022
    timeout-minutes: 5
