name: Pull Request
on:
  pull_request:
jobs:
  pull_request:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v4
    - id: tests
      name: Tests
      run: make test-ci
    - id: coverage
      if: ${{ matrix.os }} == ubuntu-20.04
      name: Coverage
      uses: gwatts/go-coverage-action@v2.0.0
    timeout-minutes: 5
    strategy:
      matrix:
        os:
        - ubuntu-24.04
        - macos-15
        - windows-2022
