# generated-by: cinzel
# cinzel-provider: github
name: Merge with Main
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  merge:
    name: Merge with main
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: "false"
    timeout-minutes: 5
